config/routes.rb
Assignment::Application.routes.draw do

  match "/reports" => 'reports#index'

  resources :results

  resources :assessments

  resources :students do
    collection do
      get 'get_sections'
    end
  end

  resources :sections

  resources :claasses

end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
  attr_accessible :assessment_name
  has_many :results
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  # GET /assessments
  # GET /assessments.json
  def index
    @assessments = Assessment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assessments }
    end
  end

  # GET /assessments/1
  # GET /assessments/1.json
  def show
    @assessment = Assessment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assessment }
    end
  end

  # GET /assessments/new
  # GET /assessments/new.json
  def new
    @assessment = Assessment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assessment }
    end
  end

  # GET /assessments/1/edit
  def edit
    @assessment = Assessment.find(params[:id])
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = Assessment.new(params[:assessment])

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to @assessment, notice: 'Assessment was successfully created.' }
        format.json { render json: @assessment, status: :created, location: @assessment }
      else
        format.html { render action: "new" }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assessments/1
  # PUT /assessments/1.json
  def update
    @assessment = Assessment.find(params[:id])

    respond_to do |format|
      if @assessment.update_attributes(params[:assessment])
        format.html { redirect_to @assessment, notice: 'Assessment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    @assessment = Assessment.find(params[:id])
    @assessment.destroy

    respond_to do |format|
      format.html { redirect_to assessments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/views/assessments/_form.html.erb
<%= form_for(@assessment) do |f| %>
  <% if @assessment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assessment.errors.count, "error") %> prohibited this assessment from being saved:</h2>

      <ul>
      <% @assessment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :assessment_name %><br />
    <%= f.text_field :assessment_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assessments/edit.html.erb
<h1>Editing assessment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assessment %> |
<%= link_to 'Back', assessments_path %>

app/views/assessments/index.html.erb
<h1>Listing assessments</h1>

<table>
  <tr>
    <th>Assessment name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assessments.each do |assessment| %>
  <tr>
    <td><%= assessment.assessment_name %></td>
    <td><%= link_to 'Show', assessment %></td>
    <td><%= link_to 'Edit', edit_assessment_path(assessment) %></td>
    <td><%= link_to 'Destroy', assessment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assessment', new_assessment_path %>

app/views/assessments/new.html.erb
<h1>New assessment</h1>

<%= render 'form' %>

<%= link_to 'Back', assessments_path %>

app/views/assessments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Assessment name:</b>
  <%= @assessment.assessment_name %>
</p>


<%= link_to 'Edit', edit_assessment_path(@assessment) %> |
<%= link_to 'Back', assessments_path %>