config/routes.rb
Assignment::Application.routes.draw do

  match "/reports" => 'reports#index'

  resources :results

  resources :assessments

  resources :students do
    collection do
      get 'get_sections'
    end
  end

  resources :sections

  resources :claasses

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :sections_id, :student_name
  belongs_to :section
  has_many :results
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new
    @cls = Claass.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  def get_sections
    section = Section.where("claasses_id = ?", params[:clas_id].to_i)
    render :json=>[section]    if section
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      Class<br />
      <%= select_tag 'class[]' , options_for_select(@cls.collect{ |u| [u.class_name, u.id] }),  :prompt => "Select Class", :id => "classs" %>
    </div>

  <div class="field">
    <%= f.label :sections_id %><br />
    <%= f.select :sections_id,'', include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :student_name %><br />
    <%= f.text_field :student_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script>
  $(document).ready(function(){

    $("#classs").on("change", function(){
        if($("#classs").val()!="")
        {
            $.get("/students/get_sections",{
                clas_id : $("#classs").val()
            }, function(data){

                if (data[0]!=null)
                {
                    $('#student_sections_id').find('option').remove().end()
                    $('#student_sections_id').append($("<option></option>").attr("value","").text("Select Section"));
                    for(var i=0; i<data[0].length;i++)
                    {
                        $('#student_sections_id').append($("<option></option>").attr("value",data[0][i].id).text(data[0][i].section_name));
                    }
                }

            })
        }

    });
  });
</script>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Sections</th>
    <th>Student name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.sections_id %></td>
    <td><%= student.student_name %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sections:</b>
  <%= @student.sections_id %>
</p>

<p>
  <b>Student name:</b>
  <%= @student.student_name %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>