config/routes.rb
Assignment::Application.routes.draw do

  match "/reports" => 'reports#index'

  resources :results

  resources :assessments

  resources :students do
    collection do
      get 'get_sections'
    end
  end

  resources :sections

  resources :claasses

end

app/models/result.rb
class Result < ActiveRecord::Base
  attr_accessible :assessment_id, :percentage, :student_id, :section_id
  belongs_to :assessment
  belongs_to :student
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  # GET /results
  # GET /results.json
  def index
    @results = Result.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @results }
    end
  end

  # GET /results/1
  # GET /results/1.json
  def show
    @result = Result.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @result }
    end
  end

  # GET /results/new
  # GET /results/new.json
  def new
    @result = Result.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @result }
    end
  end

  # GET /results/1/edit
  def edit
    @result = Result.find(params[:id])
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(params[:result])

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render json: @result, status: :created, location: @result }
      else
        format.html { render action: "new" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /results/1
  # PUT /results/1.json
  def update
    @result = Result.find(params[:id])

    respond_to do |format|
      if @result.update_attributes(params[:result])
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.collection_select :student_id,  Student.order(:student_name), :id, :student_name, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :assessment_id %><br />
    <%= f.collection_select :assessment_id,  Assessment.order(:assessment_name), :id, :assessment_name, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :percentatge %><br />
    <%= f.number_field :percentage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h1>Listing results</h1>

<table>
  <tr>
    <th>Student</th>
    <th>Assessment</th>
    <th>percentage</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @results.each do |result| %>
  <tr>
    <td><%= result.student_id %></td>
    <td><%= result.assessment_id %></td>
    <td><%= result.percentage %></td>
    <td><%= link_to 'Show', result %></td>
    <td><%= link_to 'Edit', edit_result_path(result) %></td>
    <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <%= @result.student_id %>
</p>

<p>
  <b>Assessment:</b>
  <%= @result.assessment_id %>
</p>

<p>
  <b>Percentage:</b>
  <%= @result.percentage %>
</p>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>