config/routes.rb
Assignment::Application.routes.draw do

  match "/reports" => 'reports#index'

  resources :results

  resources :assessments

  resources :students do
    collection do
      get 'get_sections'
    end
  end

  resources :sections

  resources :claasses

end

app/controllers/claasses_controller.rb
class ClaassesController < ApplicationController
  # GET /claasses
  # GET /claasses.json
  def index
    @claasses = Claass.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @claasses }
    end
  end

  # GET /claasses/1
  # GET /claasses/1.json
  def show
    @claass = Claass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @claass }
    end
  end

  # GET /claasses/new
  # GET /claasses/new.json
  def new
    @claass = Claass.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @claass }
    end
  end

  # GET /claasses/1/edit
  def edit
    @claass = Claass.find(params[:id])
  end

  # POST /claasses
  # POST /claasses.json
  def create
    @claass = Claass.new(params[:claass])

    respond_to do |format|
      if @claass.save
        format.html { redirect_to @claass, notice: 'Claass was successfully created.' }
        format.json { render json: @claass, status: :created, location: @claass }
      else
        format.html { render action: "new" }
        format.json { render json: @claass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /claasses/1
  # PUT /claasses/1.json
  def update
    @claass = Claass.find(params[:id])

    respond_to do |format|
      if @claass.update_attributes(params[:claass])
        format.html { redirect_to @claass, notice: 'Claass was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @claass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claasses/1
  # DELETE /claasses/1.json
  def destroy
    @claass = Claass.find(params[:id])
    @claass.destroy

    respond_to do |format|
      format.html { redirect_to claasses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/claasses_helper.rb
module ClaassesHelper
end

app/views/claasses/_form.html.erb
<%= form_for(@claass) do |f| %>
  <% if @claass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@claass.errors.count, "error") %> prohibited this claass from being saved:</h2>

      <ul>
      <% @claass.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :class_name %><br />
    <%= f.text_field :class_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/claasses/edit.html.erb
<h1>Editing claass</h1>

<%= render 'form' %>

<%= link_to 'Show', @claass %> |
<%= link_to 'Back', claasses_path %>

app/views/claasses/index.html.erb
<h1>Listing claasses</h1>

<table>
  <tr>
    <th>Class name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @claasses.each do |claass| %>
  <tr>
    <td><%= claass.class_name %></td>
    <td><%= link_to 'Show', claass %></td>
    <td><%= link_to 'Edit', edit_claass_path(claass) %></td>
    <td><%= link_to 'Destroy', claass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Claass', new_claass_path %>

app/views/claasses/new.html.erb
<h1>New claass</h1>

<%= render 'form' %>

<%= link_to 'Back', claasses_path %>

app/views/claasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Class name:</b>
  <%= @claass.class_name %>
</p>


<%= link_to 'Edit', edit_claass_path(@claass) %> |
<%= link_to 'Back', claasses_path %>